apiVersion: v1
kind: Service
metadata:
    labels:
        pesca.service: webserver-service
    name: webserver-service
spec:
    ports:
        - name: "23337"
          port: 23337
          targetPort: 3000
    selector:
        pesca.service: webserver-deployment
status:
    loadBalancer: {}
