apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: webserver-ingress
spec:
    rules:
        - host: rytlock.pesca.dev
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: webserver
                            port:
                                number: 23337
