apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    labels:
        io.kompose.service: webserver-db-claim0
    name: webserver-db-claim0
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 100Mi
status: {}
