name: publish

on: [push]

jobs:
    publish-hello-world-image:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GH_PAT }}
            - name: Build the hello-world Docker image
              run: |
                  docker build . --tag ghcr.io/h1ghbre4k3r/k8s-deploy:latest
                  docker run ghcr.io/h1ghbre4k3r/k8s-deploy:latest
                  docker push ghcr.io/h1ghbre4k3r/k8s-deploy:latest
